apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: atd-sftp
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: atd-sftp-api
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          httpGet:
            path: /health
            port: 80
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          httpGet:
            path: /health
            port: 80
        volumeMounts:
        - name: secret
          mountPath: "/opt/service/secret"
          readOnly: true
      volumes:
      - name: secret
        secret:
          secretName: secret
---
kind: Service
apiVersion: v1
metadata:
  name: api
  namespace: atd-sftp
  labels:
    app: api
spec:
  selector:
    app: api
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
