apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: atd-sftp-api
  namespace: atd-sftp
spec:
  selector:
    matchLabels:
      app: api
  endpoints:
  - port: http
    interval: 15s
    honorLabels: true
